imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name:   tw_session
        save_path: "%kernel.root_dir%/sessions"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        app_front_url:  "%app_front_url%"
        online_mail_dir:  "%online_mail_dir%"
        upload_avatars_dir: "%upload_avatars_dir%"
        upload_avatars_dir_temp: "%upload_avatars_dir_temp%"
        upload_bouteilles_dir: "%upload_bouteilles_dir%"
        upload_bouteilles_dir_temp: "%upload_bouteilles_dir_temp%"
        upload_selections_dir: "%upload_selections_dir%"
        upload_selections_dir_temp: "%upload_selections_dir_temp%"
        upload_mea_dir: "%upload_mea_dir%"
        upload_mea_dir_temp: "%upload_mea_dir_temp%"
        upload_presse_dir: "%upload_presse_dir%"
        upload_presse_dir_temp: "%upload_presse_dir_temp%"
        upload_partenaire_dir: "%upload_partenaire_dir%"
        upload_partenaire_dir_temp: "%upload_partenaire_dir_temp%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        
        dql:
            string_functions:
                acos: DoctrineExtensions\Query\Mysql\Acos
                asin: DoctrineExtensions\Query\Mysql\Asin
                atan2: DoctrineExtensions\Query\Mysql\Atan2
                atan: DoctrineExtensions\Query\Mysql\Atan
                charlength: DoctrineExtensions\Query\Mysql\CharLength
                concatws: DoctrineExtensions\Query\Mysql\ConcatWs
                cos: DoctrineExtensions\Query\Mysql\Cos
                cot: DoctrineExtensions\Query\Mysql\Cot
                countif: DoctrineExtensions\Query\Mysql\CountIf
                dateadd: DoctrineExtensions\Query\Mysql\DateAdd
                datediff: DoctrineExtensions\Query\Mysql\DateDiff
                day: DoctrineExtensions\Query\Mysql\Day
                degrees: DoctrineExtensions\Query\Mysql\Degrees
                field: DoctrineExtensions\Query\Mysql\Field
                findinset: DoctrineExtensions\Query\Mysql\FindInSet
                groupconcat: DoctrineExtensions\Query\Mysql\GroupConcat
                ifelse: DoctrineExtensions\Query\Mysql\IfElse
                ifnull: DoctrineExtensions\Query\Mysql\IfNull
                matchagainst: DoctrineExtensions\Query\Mysql\MatchAgainst
                md5: DoctrineExtensions\Query\Mysql\Md5
                month: DoctrineExtensions\Query\Mysql\Month
                nullif: DoctrineExtensions\Query\Mysql\NullIf
                radians: DoctrineExtensions\Query\Mysql\Radians
                sha1: DoctrineExtensions\Query\Mysql\Sha1
                sha2: DoctrineExtensions\Query\Mysql\Sha2
                sin: DoctrineExtensions\Query\Mysql\Sin
                strtodate: DoctrineExtensions\Query\Mysql\StrToDate
                tan: DoctrineExtensions\Query\Mysql\Tan
                timestampdiff: DoctrineExtensions\Query\Mysql\TimestampDiff
                week: DoctrineExtensions\Query\Mysql\Week
                year: DoctrineExtensions\Query\Mysql\Year

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    #spool:     { type: memory }
    port:      "%mailer_port%"
    encryption: "%mailer_encryption%"
    auth_mode:  "%mailer_auth_mode%"
    
# FOSUser
fos_user:
    db_driver: orm 
    firewall_name: BO
    user_class: AppBundle\Entity\Administrator
    
#Easy Admin
easy_admin:
    entities:
        - AppBundle\Entity\Administrator
        - AppBundle\Entity\Member
        - AppBundle\Entity\Bouteille
        - AppBundle\Entity\TypeAppellation
        - AppBundle\Entity\TypeContenance
        - AppBundle\Entity\TypeCuvee
        - AppBundle\Entity\TypeDeCave
        - AppBundle\Entity\TypeDeVin
        - AppBundle\Entity\TypeDomaine
        - AppBundle\Entity\TypePays
        - AppBundle\Entity\TypeRegion
        - AppBundle\Entity\Image

# KNP Pagniator
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
        
#LIIP RESIZE
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: uploads/media/cache

    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    
    filter_sets:        
        bouteille_resize_fiche:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [200, 320], mode: outbound }
        bouteille_resize_cave:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [142, 230], mode: outbound }
        bouteille_resize_messagerie:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [42, 62], mode: outbound }
        avatar_resize_cave:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [170, 170], mode: outbound }
        avatar_resize_header:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [130, 130], mode: outbound }
        avatar_resize_mini:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [65, 65], mode: outbound }
        avatar_resize_messagerie:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [75, 75], mode: outbound }
        homepage_mea:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [228, 228], mode: outbound }
        homepage_selection_1:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [475, 230], mode: outbound }
        homepage_selection_2:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [230, 475], mode: outbound }
        homepage_selection_3:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [230, 230], mode: outbound }
        homepage_selection_4:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [230, 230], mode: outbound }
        section_presse:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [175, 175], mode: outbound }
        section_partenaire:
            quality: 75
            cache: ~
            filters:
                auto_rotate: ~
                thumbnail: { size: [175, 175], mode: outbound }
