# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        AppBundle\Entity\Member: 
            algorithm : sha512
            encode_as_base64: true
            iterations: 5000

    role_hierarchy:
        ROLE_MEMBRE: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_MEMBRE]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        my_database_provider:
            entity:
                class: AppBundle:Member
                property: login

    firewalls:        
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        
        #BO:
        #    pattern: ^/admin
        #    form_login:
        #        provider: fos_userbundle
        #        csrf_provider: security.csrf.token_manager 
        #        login_path: fos_user_security_login
        #        check_path: fos_user_security_check
        #        default_target_path: /admin
        #    logout:
        #        path:   fos_user_security_logout
        #        target: /admin
        #    anonymous:    true
        
        BO:
            pattern: ^/admin
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager 
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /admin
            logout:
                path:   fos_user_security_logout
                target: /admin
            anonymous:    true
        
        BODev:
            pattern: ^/admin-dev
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager 
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /admin-dev
            logout:
                path:   fos_user_security_logout
                target: /admin-dev
            anonymous:    true
            
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
            
        app:
            pattern: ^/
            anonymous: ~
            form_login:  # Authentication mecanism
                provider: my_database_provider  
                csrf_provider: form.csrf_provider
                check_path: login_check
                login_path: login
                use_referer:    true
                success_handler: app.authentication_handler
                failure_handler: app.authentication_handler
            logout:
                path:   /logout
                target: /homepage          

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ma-cave/$, role: [ROLE_MEMBRE] }
        - { path: ^/mon-profil/$, role: [ROLE_MEMBRE] }
        - { path: ^/admin/, role: [ROLE_ADMIN] }
