# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.vars_extension:
         class: AppBundle\Twig\VarsExtension
         tags:
             - { name: twig.extension }
         arguments: ["@service_container", %locale%]