<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRdvRepository extends EntityRepository
{
    
    public function findAllNotChecked(){
        $query = $this->createQueryBuilder('a')
                    ->where('a.name IS NOT NULL')
                    ->andWhere('a.checkedForSuggestion IS NULL');
        
        return $query->getQuery()->getResult();
    }
    
}
