<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeContenanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeContenanceRepository extends EntityRepository
{
}
