back_office_type_contenances:
    path:     /
    defaults: { _controller: "BackOfficeBundle:TypeContenance:index" }

back_office_type_contenance_show:
    path:     /{id}/show
    defaults: { _controller: "BackOfficeBundle:TypeContenance:show" } 

back_office_type_contenance_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:TypeContenance:new" }

back_office_type_contenance_create:
    path:     /create
    defaults: { _controller: "BackOfficeBundle:TypeContenance:create" }
    methods:  POST

back_office_type_contenance_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackOfficeBundle:TypeContenance:edit" }

back_office_type_contenance_update:
    path:     /{id}/update
    defaults: { _controller: "BackOfficeBundle:TypeContenance:update" }
    methods:  [POST, PUT] 

back_office_type_contenance_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackOfficeBundle:TypeContenance:delete" }
    methods:  [POST, DELETE]  